#
# (C) Copyright 2018
# NVIDIA Corporation <www.nvidia.com>
#
# SPDX-License-Identifier:     GPL-2.0+
#

obj-y	+= p3450-0000.o
obj-y	+= emc-table.o
obj-y	+= minerva/
obj-$(CONFIG_ARMV8_PSCI)	+= psci.o psci_secondary.o
